version: '2'
services:
  vulnerable_node:
    restart: always
    build: .
    ports:
      - "3000:3000"
#    links:
#      - postgres_db:postgres_db
    depends_on:
      - postgres_db

  postgres_db:
    restart: always
    build: ./services/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
